1.进行获取参数/Api/sand/getprolist
            'product_code' => $product_code,
            'product_season_name' => $product_season_name,
            'product_season_name_spa' => $product_season_name_spa,
            'product_year_name' => $product_year_name,
            'region_name' => $region_name,
            'brand_no' => $brand_no,
            'city' => $city,
            'week_in_year' => $new_week,
            'ref_region' => $ref_region,
            'order_city' => $order_city,
            'cnt_start' => $cnt_start,
            'cnt_end' => $cnt_end,
            'category_name1' => $category_name1,
            'category_name2' => $category_name2,
            'category_name3' => $category_name3,
            'dev_attribute_name' => $dev_attribute_name,
            'supplier_type_name' => $supplier_type_name,
            'is_city_rep' => $is_city_rep,
            'is_all' => $is_all,
            'def1' => $def1,
            'def2' => $def2,
            're_pro' => $re_pro,
            're_act' => $re_act,
            'act' => $act,
            'pri' => $pri,
            'gui' => $gui,
            'gui_note' => $gui_note,
            'act_rep' => $act_rep,
            'act_transfer' => $act_transfer,
            'act_in_goods_city' => $act_in_goods_city,
            'act_in_goods' => $act_in_goods,
            'type_here' => $type_here,
            'lining_name' => $lining_name,
            'pro_label_type' => $pro_label_type,
            'ordertype' => $ordertype,
            'orders' => $orders,
            'page' => $page,
            'pagesize' => $pagesize,


2./Api/sand/getprolist调用getSandInfo方法
       